# -*- coding: utf-8 -*-
"""API twitter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LgTYdO2fcfFQcMw4Y0zMq58QMAZdq85e
"""

# The following instruction is used to install a given library
#!pip install library_name
!pip install tweepy # to install the tweepy library

# Useful Modules

import tweepy as tw # used to extract data from twitter
import pandas as pd # used to create a pandas dataframe
import json # used to load the json files

import json

def load_credentials(file_path):
    with open(file_path) as json_file:
        credentials = json.load(json_file)
    return credentials

file_path= "/content/twiter_API.json"
credentials=load_credentials(file_path)

def get_API(credentials):
    auth = tw.OAuthHandler(credentials['consumer_key'], credentials['consumer_secret'])
    auth.set_access_token(credentials['access_token'], credentials['access_token_secret'])

    return tw.API(auth, wait_on_rate_limit=True)

credentials = load_credentials("/content/twiter_API.json")
api = get_API(credentials)

import tweepy as tw
def search_tweets(search_word, date_since, limit=20):
    """
        search_word: the topic we want to search about (e.g. covid19)
        data_since: the date from when we want the information related to "search_word"
        limit: used to restrict the number of tweets to be returned. If not specified, it will retrive all the Tweets
    @return:
        tweets_cursor: a cursor used to paginate through the large retrieved data
    """
    tweets_cursor = tw.Cursor(api.search_tweets,
              q=search_words,
              lang="fr",
              since=date_since).items(limit)

    return tweets_cursor

search_words = "#onepiece"
date_since = "2024-04-29"

ONE_cursor = search_tweets(search_words, date_since)

ONE_cursor

for tweet in ONE_cursor:
    print(tweet.text)